### ISSUE TITLE
Public Key >> Authorized Keys?

### ISSUE THREAD

**Issue by K4KDR** [ceyzeriat/nanosat-control#1]
During the install process, the following statement is presented:

==========================
Before continuing, you will need to copy your public key shown below to the authorized keys of the user 'picsatdata' on gitlab.obspm.fr
==========================

... what is the means to accomplish that?

Many thanks!

**Comment by ceyzeriat** [comment]
Hi K4KDR! and thanks for your interest in PICSAT!
I should definitely edit the README of this repo.

Alright, so, I developed the ground segment software for PICSAT with the idea to create not just a one-off ground segment software, but a generic solution to any cubesat mission, like a framework. This ground segment is split into 2 parts: the specific parametrization of the cubesat, and the framework/software.
This nanosat-control repo contains this open-source framework.. which cannot work without the specific parameters of the cubesat, obviously.
If your aim was to unpack the raw-octets frames of the PICSAT mission into a data-structure of key-values, which I expect it was, then essentially this repo is useless for you as the parametrization of picsat ground segment is not public.
And since I lacked time a lot lately, I did not create an example-repo of parametrization for this ground segment framework, so sadly this repo is nearly completely useless (I must admit it would not take much time at all to create an example-parametrization, and I should really do it).

So the error you see is due to the install.sh script being outdated - the key-thing was aiming at pulling code, which now should be replaced by pulling the code from this repo.

However, if your aim is indeed to unpack the raw-octets frames of the PICSAT mission, keep reading :)

Since the PICSAT mission is using amateur bands, the format of TC and TM should (must?) be public: anyone should be able to unpack the TM data using the code in this repo, and the public TM format.
Better: I separated the pieces of code that unpacks the TM from the rest of this ground segment (as you would expect this ground segment code does much more than just unpacking TM), and I (and the picsat team) expect to release a new repo that contain everything needed to unpack a raw octet-frame.
Something like:
>>> from picunpack import unpack
>>> unpack(filename, or string, or bytes)
>>> "json-structure"

I also thinking about making a binary for command-line usage:
>>> picunpack packet.kss -o packet.json

**Comment by K4KDR** [comment]
Thank you very much for the reply!  I already am decoding the raw hex data from PicSat and have uploaded a number of packets to the website.  I found this repository and was just looking to see if it provided any additional functionality.   Of course I understand that the entire project is a work-in-progress.  Thank you again for the additional information.  Best of luck!  

-Scott,  K4KDR

**Comment by ceyzeriat** [comment]
Decision was made to not release the comm protocols besides a pdf version of the beacon structure, so I guess that's the end of the story on self-unpacking the TM. There will be the website to provide this functionality though.
Sorry for that - not my call
